/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import App.Connect;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.MongoIterable;
import App.RoundedPanel;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;
import java.util.Random;
import org.bson.Document;
import org.bson.types.ObjectId;
/**
 *
 * @author LENOVO
 */
public class Add extends javax.swing.JFrame {
    MainActivity main = new MainActivity();
    /**
     * Creates new form Tambah
     */
    public Add() {
        setUndecorated(true);
        setIcon();
        initComponents();
        
        setTitle("Add Data");
        // Rounded corners
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        CloseBtn = new javax.swing.JLabel();
        RoundPanel = new RoundedPanel(25, new Color(0, 0, 0, 50));
        welcomeJL = new javax.swing.JLabel();
        usernameJL = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AddBtn = new App.ButtonGradient();
        namaBuku = new javax.swing.JTextField();
        passwordJL2 = new javax.swing.JLabel();
        passwordJL3 = new javax.swing.JLabel();
        genreTxt = new javax.swing.JTextField();
        hargaTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(0, 0, 0, 0)
        );

        kGradientPanel1.setkEndColor(new java.awt.Color(22, 191, 253));
        kGradientPanel1.setkStartColor(new java.awt.Color(203, 48, 102));

        CloseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/Group 1.png"))); // NOI18N
        CloseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CloseBtnMousePressed(evt);
            }
        });

        RoundPanel.setForeground(new java.awt.Color(51, 51, 51));
        RoundPanel.setOpaque(false);
        RoundPanel.setPreferredSize(new java.awt.Dimension(360, 400));

        welcomeJL.setFont(new java.awt.Font("Cantarell", 1, 20)); // NOI18N
        welcomeJL.setForeground(new java.awt.Color(170, 117, 255));
        welcomeJL.setText("Adding Data");

        usernameJL.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        usernameJL.setForeground(new java.awt.Color(239, 239, 239));
        usernameJL.setText("Nama Buku");

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter data in the table");

        AddBtn.setText("Add Data");
        AddBtn.setColor1(new java.awt.Color(0, 204, 204));
        AddBtn.setColor2(new java.awt.Color(204, 0, 204));
        AddBtn.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        namaBuku.setBackground(new Color(0, 0, 0, 0));
        namaBuku.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        namaBuku.setForeground(new java.awt.Color(255, 255, 255));
        namaBuku.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 126, 250)));
        namaBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaBukuActionPerformed(evt);
            }
        });

        passwordJL2.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        passwordJL2.setForeground(new java.awt.Color(239, 239, 239));
        passwordJL2.setText("Genre");

        passwordJL3.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        passwordJL3.setForeground(new java.awt.Color(239, 239, 239));
        passwordJL3.setText("Harga");

        genreTxt.setBackground(new Color(0, 0, 0, 0));
        genreTxt.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        genreTxt.setForeground(new java.awt.Color(255, 255, 255));
        genreTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 126, 250)));
        genreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreTxtActionPerformed(evt);
            }
        });

        hargaTxt.setBackground(new Color(0, 0, 0, 0));
        hargaTxt.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        hargaTxt.setForeground(new java.awt.Color(255, 255, 255));
        hargaTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 126, 250)));
        hargaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RoundPanelLayout = new javax.swing.GroupLayout(RoundPanel);
        RoundPanel.setLayout(RoundPanelLayout);
        RoundPanelLayout.setHorizontalGroup(
            RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoundPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(namaBuku, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genreTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hargaTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RoundPanelLayout.createSequentialGroup()
                        .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordJL3)
                            .addComponent(usernameJL)
                            .addComponent(passwordJL2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoundPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoundPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoundPanelLayout.createSequentialGroup()
                        .addComponent(welcomeJL)
                        .addGap(188, 188, 188))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        RoundPanelLayout.setVerticalGroup(
            RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoundPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(welcomeJL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(22, 22, 22)
                .addComponent(usernameJL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordJL2)
                .addGap(4, 4, 4)
                .addComponent(genreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordJL3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(RoundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CloseBtn)
                .addGap(20, 20, 20))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RoundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMousePressed
        this.dispose();
    }//GEN-LAST:event_CloseBtnMousePressed

    private void hargaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaTxtActionPerformed

    private void genreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreTxtActionPerformed

    private void namaBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaBukuActionPerformed
        // TODO add your handling code here:
        if (namaBuku.getText().isEmpty()) {
            namaBuku.requestFocus();
        }else{
            //            loginProcess();
        }
    }//GEN-LAST:event_namaBukuActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        String nama_buku = namaBuku.getText();
        String genre = genreTxt.getText();
        String harga = hargaTxt.getText();
        
        if (nama_buku.isEmpty() || genre.isEmpty() || harga.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please complete the data according to the table!");
            this.requestFocus();
        }else{
            Random rand = new Random();
            Document buku = new Document("_id", new ObjectId());
            buku.append("book_name", nama_buku)
                   .append("genre", genre)
                   .append("price", harga);
             MongoDatabase db = Connect.connectDB();
//                MongoIterable<String> tables = db.listCollectionNames();                
                MongoCollection<Document> coll = db.getCollection("book_list");
            coll.insertOne(buku);
            JOptionPane.showMessageDialog(this, "Data added successfully");
            main.loadData("");
            this.dispose();
//        String nama_umkm = namaBuku.getText();
//        String pemilik = genreTxt.getText();
//        String bidang = bidangUmkm.getSelectedItem().toString();
//        String jenis = jenisUmkm.getSelectedItem().toString();
//        String alamat = hargaTxt.getText();
//        String kota_kab = kotaKab.getSelectedItem().toString();
//
//        if (nama_umkm.isEmpty() || pemilik.isEmpty() || bidang.isEmpty() || jenis.isEmpty() || alamat.isEmpty() || kota_kab.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Please complete the data according to the table!");
//            this.requestFocus();
//        }else{
            //            try {
                //                Connection c = Connect.MySQl();
                //                Statement st = c.createStatement();
                //                String query = "INSERT INTO umkm (nama_umkm, jenis_umkm, bidang_umkm, pemilik_umkm, alamat_umkm, kota_kabupaten) VALUES ('"+nama_umkm+"','"+jenis+"','"+bidang+"','"+pemilik+"','"+alamat+"','"+kota_kab+"')";
                //                st.executeUpdate(query);
                //                JOptionPane.showMessageDialog(this, "Data added successfully");
                //                MainActivity main = new MainActivity();
                //                main.loadData("");
                //                this.dispose();
                //            } catch (SQLException e) {
                //                JOptionPane.showMessageDialog(this, e.getMessage());
                //            }

        }
    }//GEN-LAST:event_AddBtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Add().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private App.ButtonGradient AddBtn;
    private javax.swing.JLabel CloseBtn;
    private javax.swing.JPanel RoundPanel;
    private javax.swing.JTextField genreTxt;
    private javax.swing.JTextField hargaTxt;
    private javax.swing.JLabel jLabel5;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField namaBuku;
    private javax.swing.JLabel passwordJL2;
    private javax.swing.JLabel passwordJL3;
    private javax.swing.JLabel usernameJL;
    private javax.swing.JLabel welcomeJL;
    // End of variables declaration//GEN-END:variables

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Resource/Icon-frame.png")));
    }

}
