/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author LENOVO
 */
public class Update extends javax.swing.JFrame {
    
    Resources umkm;
    /**
     * Creates new form Tambah
     */
    public Update(Resources d) {
        setUndecorated(true);
        setIcon();
        initComponents();
        
        umkm = d;
        namaUmkm.setText(umkm.getNama_umkm());
        jenisUmkm.setSelectedItem(umkm.getJenis_umkm());
        bidangUmkm.setSelectedItem(umkm.getBidang_umkm());
        namaPemilik.setText(umkm.getPemilik_umkm());
        alamatUmkm.setText(umkm.getAlamat_umkm());
        kotaKab.setSelectedItem(umkm.getKota_kabupaten());
       
        setTitle("Update Data");
        // Rounded corners
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
    }

    private Update() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel7 = new javax.swing.JLabel();
        RoundPanel = new RoundedPanel(25, new Color(0, 0, 0, 50));
        welcomeJL = new javax.swing.JLabel();
        usernameJL = new javax.swing.JLabel();
        passwordJL = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        UpdateBtn = new App.ButtonGradient();
        namaUmkm = new javax.swing.JTextField();
        passwordJL1 = new javax.swing.JLabel();
        passwordJL2 = new javax.swing.JLabel();
        jenisUmkm = new javax.swing.JComboBox<>();
        bidangUmkm = new javax.swing.JComboBox<>();
        passwordJL3 = new javax.swing.JLabel();
        namaPemilik = new javax.swing.JTextField();
        alamatUmkm = new javax.swing.JTextField();
        passwordJL4 = new javax.swing.JLabel();
        kotaKab = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(0, 0, 0, 0)
        );

        kGradientPanel1.setkEndColor(new java.awt.Color(22, 191, 253));
        kGradientPanel1.setkStartColor(new java.awt.Color(203, 48, 102));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/Group 1.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });

        RoundPanel.setForeground(new java.awt.Color(51, 51, 51));
        RoundPanel.setOpaque(false);
        RoundPanel.setPreferredSize(new java.awt.Dimension(360, 400));

        welcomeJL.setFont(new java.awt.Font("Cantarell", 1, 20)); // NOI18N
        welcomeJL.setForeground(new java.awt.Color(170, 117, 255));
        welcomeJL.setText("Updating Data");

        usernameJL.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        usernameJL.setForeground(new java.awt.Color(239, 239, 239));
        usernameJL.setText("Nama UMKM");

        passwordJL.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        passwordJL.setForeground(new java.awt.Color(239, 239, 239));
        passwordJL.setText("Jenis UMKM");

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("update existing data in the table");

        UpdateBtn.setText("Update Data");
        UpdateBtn.setColor1(new java.awt.Color(204, 0, 204));
        UpdateBtn.setColor2(new java.awt.Color(0, 204, 204));
        UpdateBtn.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        namaUmkm.setBackground(new Color(0, 0, 0, 0));
        namaUmkm.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        namaUmkm.setForeground(new java.awt.Color(255, 255, 255));
        namaUmkm.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 126, 250)));
        namaUmkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaUmkmActionPerformed(evt);
            }
        });

        passwordJL1.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        passwordJL1.setForeground(new java.awt.Color(239, 239, 239));
        passwordJL1.setText("Bidang UMKM");

        passwordJL2.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        passwordJL2.setForeground(new java.awt.Color(239, 239, 239));
        passwordJL2.setText("Nama Pemilik");

        jenisUmkm.setBackground(new Color(0, 0, 0, 0)
        );
        jenisUmkm.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jenisUmkm.setForeground(new java.awt.Color(255, 255, 255));
        jenisUmkm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Usaha Mikro", "Usaha Kecil", "Usaha Menengah" }));
        jenisUmkm.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 126, 250)));
        jenisUmkm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        bidangUmkm.setBackground(new Color(0, 0, 0, 0)
        );
        bidangUmkm.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        bidangUmkm.setForeground(new java.awt.Color(255, 255, 255));
        bidangUmkm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Makanan/Minuman", "Fashion", "Kesehatan", "Jasa", "Elektronik", "Aksesoris/Kosmetik", "Perlengkapan Rumah Tangga", "Besi/Bahan Bangunan", "Furniture/Int/Eksterior", "Peternakan", "Hasil Tani", "Lembaga Keuangan" }));
        bidangUmkm.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 126, 250)));
        bidangUmkm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bidangUmkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidangUmkmActionPerformed(evt);
            }
        });

        passwordJL3.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        passwordJL3.setForeground(new java.awt.Color(239, 239, 239));
        passwordJL3.setText("Alamat UMKM");

        namaPemilik.setBackground(new Color(0, 0, 0, 0));
        namaPemilik.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        namaPemilik.setForeground(new java.awt.Color(255, 255, 255));
        namaPemilik.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 126, 250)));
        namaPemilik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPemilikActionPerformed(evt);
            }
        });

        alamatUmkm.setBackground(new Color(0, 0, 0, 0));
        alamatUmkm.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        alamatUmkm.setForeground(new java.awt.Color(255, 255, 255));
        alamatUmkm.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 126, 250)));
        alamatUmkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatUmkmActionPerformed(evt);
            }
        });

        passwordJL4.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        passwordJL4.setForeground(new java.awt.Color(239, 239, 239));
        passwordJL4.setText("Kota/Kabupaten");

        kotaKab.setBackground(new Color(0, 0, 0, 0)
        );
        kotaKab.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        kotaKab.setForeground(new java.awt.Color(255, 255, 255));
        kotaKab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Kabupaten Tegal", "Kota Tegal" }));
        kotaKab.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 126, 250)));
        kotaKab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout RoundPanelLayout = new javax.swing.GroupLayout(RoundPanel);
        RoundPanel.setLayout(RoundPanelLayout);
        RoundPanelLayout.setHorizontalGroup(
            RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoundPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RoundPanelLayout.createSequentialGroup()
                        .addComponent(passwordJL4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoundPanelLayout.createSequentialGroup()
                        .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kotaKab, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namaUmkm, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RoundPanelLayout.createSequentialGroup()
                                .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordJL1)
                                    .addComponent(bidangUmkm, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordJL)
                                    .addComponent(jenisUmkm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(namaPemilik, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alamatUmkm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RoundPanelLayout.createSequentialGroup()
                                .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordJL3)
                                    .addComponent(usernameJL)
                                    .addComponent(passwordJL2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(50, 50, 50))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoundPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoundPanelLayout.createSequentialGroup()
                        .addComponent(welcomeJL)
                        .addGap(174, 174, 174))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoundPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(126, 126, 126))))
        );
        RoundPanelLayout.setVerticalGroup(
            RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoundPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(welcomeJL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(23, 23, 23)
                .addComponent(usernameJL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaUmkm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordJL2)
                .addGap(4, 4, 4)
                .addComponent(namaPemilik, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordJL1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordJL, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bidangUmkm, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jenisUmkm, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(passwordJL3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alamatUmkm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordJL4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kotaKab, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(RoundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(20, 20, 20))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RoundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        this.dispose();
    }//GEN-LAST:event_jLabel7MousePressed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
        
        String nama_umkm = namaUmkm.getText();
        String pemilik = namaPemilik.getText();
        String bidang = bidangUmkm.getSelectedItem().toString();
        String jenis = jenisUmkm.getSelectedItem().toString();
        String alamat = alamatUmkm.getText();
        String kota_kab = kotaKab.getSelectedItem().toString();
        
        if (nama_umkm.isEmpty()) {
            JOptionPane.showMessageDialog(this, "nama tidak boleh kosong");
            namaUmkm.requestFocus();
        }else{
//            try {
//                Connection c = Connect.MySQl();
//                Statement st = c.createStatement();
//                String query = "UPDATE umkm SET nama_umkm='"+nama_umkm+"', jenis_umkm='"+jenis+"', bidang_umkm='"+bidang+"', pemilik_umkm='"+pemilik+"', alamat_umkm='"+alamat+"', kota_kabupaten='"+kota_kab+"' WHERE id_umkm="+umkm.getId_umkm()+"";
//                st.executeUpdate(query);
//                JOptionPane.showMessageDialog(this, "Data updated successfully!");
//                MainActivity main = new MainActivity();
//                main.loadData("");
//                this.dispose();
//            } catch (SQLException e) {
//                JOptionPane.showMessageDialog(this, e.getMessage());
//            }

        }
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void namaUmkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaUmkmActionPerformed
        // TODO add your handling code here:
        if (namaUmkm.getText().isEmpty()) {
            namaUmkm.requestFocus();
        }else{
//            loginProcess();
        }
    }//GEN-LAST:event_namaUmkmActionPerformed

    private void bidangUmkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidangUmkmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bidangUmkmActionPerformed

    private void namaPemilikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPemilikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPemilikActionPerformed

    private void alamatUmkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatUmkmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatUmkmActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Update().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RoundPanel;
    private App.ButtonGradient UpdateBtn;
    private javax.swing.JTextField alamatUmkm;
    private javax.swing.JComboBox<String> bidangUmkm;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> jenisUmkm;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JComboBox<String> kotaKab;
    private javax.swing.JTextField namaPemilik;
    private javax.swing.JTextField namaUmkm;
    private javax.swing.JLabel passwordJL;
    private javax.swing.JLabel passwordJL1;
    private javax.swing.JLabel passwordJL2;
    private javax.swing.JLabel passwordJL3;
    private javax.swing.JLabel passwordJL4;
    private javax.swing.JLabel usernameJL;
    private javax.swing.JLabel welcomeJL;
    // End of variables declaration//GEN-END:variables

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Resource/Icon-frame.png")));
    }
}
